# This is a basic workflow to help you get started with Actions

name: Encrypt Files

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  encrypt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: true  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 3 # otherwise, there would be errors pushing refs to the destination repository.
    - uses: actions/setup-python@v4.2.0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Encrypt index.html
      run: |
        npm i -D pagecrypt
        npx pagecrypt ./src/hub.html ./docs/hub.html ${{ secrets.password }}
    - name: Commit files
      run: |
        git add .
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
